-- Create the ensiklo_hpg table for HPG encyclopedia
create table ensiklo_hpg (
  id bigint generated by default as identity primary key,
  name text not null,
  threat_type text not null, -- 'hama', 'penyakit', 'gulma'
  description text,
  symptoms text,
  solution text,
  prevention text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table ensiklo_hpg enable row level security;

-- RLS Policy - allow public read access for encyclopedia data
create policy "Allow public read access for encyclopedia data"
  on ensiklo_hpg for select
  using (true);

-- Create indexes for better performance
create index idx_ensiklo_hpg_threat_type on ensiklo_hpg(threat_type);
create index idx_ensiklo_hpg_name on ensiklo_hpg(name);