-- Create the soil_properties table
create table soil_properties (
  id bigint generated by default as identity primary key,
  plot_id bigint not null references plots(id) on delete cascade,
  clay double precision[],
  silt double precision[],
  sand double precision[],
  phh2o double precision[],
  organic_carbon double precision[],
  bulk_density double precision[],
  coarse_fragments double precision[],
  cation_exchange_capacity double precision[],
  depth_intervals text[], -- To store depth interval strings like ['0-5cm', '5-15cm', '15-30cm', etc.]
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table soil_properties enable row level security;

-- RLS Policy - Users can view soil properties for their plots
create policy "Users can view soil properties for their plots"
  on soil_properties for select
  using (
    plot_id in (
      select id 
      from plots 
      where farmer_id in (
        select farmer_id 
        from user_farmers 
        where user_id = auth.jwt() ->> 'sub'
      )
    )
  );

-- RLS Policy - Users can insert soil properties for their plots
create policy "Users can insert soil properties for their plots"
  on soil_properties for insert
  with check (
    plot_id in (
      select id 
      from plots 
      where farmer_id in (
        select farmer_id 
        from user_farmers 
        where user_id = auth.jwt() ->> 'sub'
      )
    )
  );

-- RLS Policy - Users can update soil properties for their plots
create policy "Users can update soil properties for their plots"
  on soil_properties for update
  using (
    plot_id in (
      select id 
      from plots 
      where farmer_id in (
        select farmer_id 
        from user_farmers 
        where user_id = auth.jwt() ->> 'sub'
      )
    )
  );

-- RLS Policy - Users can delete soil properties for their plots
create policy "Users can delete soil properties for their plots"
  on soil_properties for delete
  using (
    plot_id in (
      select id 
      from plots 
      where farmer_id in (
        select farmer_id 
        from user_farmers 
        where user_id = auth.jwt() ->> 'sub'
      )
    )
  );

-- Create index for better performance
create index idx_soil_properties_plot_id on soil_properties(plot_id);